/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicFlagsRouteImport } from './routes/api/public/flags'
import { Route as ApiInternalFlagsRouteImport } from './routes/api/internal/flags'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiPublicFlagsCapabilityNameRouteImport } from './routes/api/public/flags.$capabilityName'
import { Route as ApiInternalFlagsHistoryRouteImport } from './routes/api/internal/flags.history'
import { Route as ApiInternalFlagsCapabilityNameRouteImport } from './routes/api/internal/flags.$capabilityName'
import { Route as ApiPublicFlagsCapabilityNameControlNameRouteImport } from './routes/api/public/flags.$capabilityName.$controlName'
import { Route as ApiInternalFlagsCapabilityNameControlNameRouteImport } from './routes/api/internal/flags.$capabilityName.$controlName'
import { Route as ApiInternalFlagsCapabilityNameControlNameHistoryRouteImport } from './routes/api/internal/flags.$capabilityName.$controlName.history'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFlagsRoute = ApiPublicFlagsRouteImport.update({
  id: '/api/public/flags',
  path: '/api/public/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalFlagsRoute = ApiInternalFlagsRouteImport.update({
  id: '/api/internal/flags',
  path: '/api/internal/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFlagsCapabilityNameRoute =
  ApiPublicFlagsCapabilityNameRouteImport.update({
    id: '/$capabilityName',
    path: '/$capabilityName',
    getParentRoute: () => ApiPublicFlagsRoute,
  } as any)
const ApiInternalFlagsHistoryRoute = ApiInternalFlagsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ApiInternalFlagsRoute,
} as any)
const ApiInternalFlagsCapabilityNameRoute =
  ApiInternalFlagsCapabilityNameRouteImport.update({
    id: '/$capabilityName',
    path: '/$capabilityName',
    getParentRoute: () => ApiInternalFlagsRoute,
  } as any)
const ApiPublicFlagsCapabilityNameControlNameRoute =
  ApiPublicFlagsCapabilityNameControlNameRouteImport.update({
    id: '/$controlName',
    path: '/$controlName',
    getParentRoute: () => ApiPublicFlagsCapabilityNameRoute,
  } as any)
const ApiInternalFlagsCapabilityNameControlNameRoute =
  ApiInternalFlagsCapabilityNameControlNameRouteImport.update({
    id: '/$controlName',
    path: '/$controlName',
    getParentRoute: () => ApiInternalFlagsCapabilityNameRoute,
  } as any)
const ApiInternalFlagsCapabilityNameControlNameHistoryRoute =
  ApiInternalFlagsCapabilityNameControlNameHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ApiInternalFlagsCapabilityNameControlNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/internal/flags': typeof ApiInternalFlagsRouteWithChildren
  '/api/public/flags': typeof ApiPublicFlagsRouteWithChildren
  '/api/internal/flags/$capabilityName': typeof ApiInternalFlagsCapabilityNameRouteWithChildren
  '/api/internal/flags/history': typeof ApiInternalFlagsHistoryRoute
  '/api/public/flags/$capabilityName': typeof ApiPublicFlagsCapabilityNameRouteWithChildren
  '/api/internal/flags/$capabilityName/$controlName': typeof ApiInternalFlagsCapabilityNameControlNameRouteWithChildren
  '/api/public/flags/$capabilityName/$controlName': typeof ApiPublicFlagsCapabilityNameControlNameRoute
  '/api/internal/flags/$capabilityName/$controlName/history': typeof ApiInternalFlagsCapabilityNameControlNameHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/internal/flags': typeof ApiInternalFlagsRouteWithChildren
  '/api/public/flags': typeof ApiPublicFlagsRouteWithChildren
  '/api/internal/flags/$capabilityName': typeof ApiInternalFlagsCapabilityNameRouteWithChildren
  '/api/internal/flags/history': typeof ApiInternalFlagsHistoryRoute
  '/api/public/flags/$capabilityName': typeof ApiPublicFlagsCapabilityNameRouteWithChildren
  '/api/internal/flags/$capabilityName/$controlName': typeof ApiInternalFlagsCapabilityNameControlNameRouteWithChildren
  '/api/public/flags/$capabilityName/$controlName': typeof ApiPublicFlagsCapabilityNameControlNameRoute
  '/api/internal/flags/$capabilityName/$controlName/history': typeof ApiInternalFlagsCapabilityNameControlNameHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/internal/flags': typeof ApiInternalFlagsRouteWithChildren
  '/api/public/flags': typeof ApiPublicFlagsRouteWithChildren
  '/api/internal/flags/$capabilityName': typeof ApiInternalFlagsCapabilityNameRouteWithChildren
  '/api/internal/flags/history': typeof ApiInternalFlagsHistoryRoute
  '/api/public/flags/$capabilityName': typeof ApiPublicFlagsCapabilityNameRouteWithChildren
  '/api/internal/flags/$capabilityName/$controlName': typeof ApiInternalFlagsCapabilityNameControlNameRouteWithChildren
  '/api/public/flags/$capabilityName/$controlName': typeof ApiPublicFlagsCapabilityNameControlNameRoute
  '/api/internal/flags/$capabilityName/$controlName/history': typeof ApiInternalFlagsCapabilityNameControlNameHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/internal/flags'
    | '/api/public/flags'
    | '/api/internal/flags/$capabilityName'
    | '/api/internal/flags/history'
    | '/api/public/flags/$capabilityName'
    | '/api/internal/flags/$capabilityName/$controlName'
    | '/api/public/flags/$capabilityName/$controlName'
    | '/api/internal/flags/$capabilityName/$controlName/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/internal/flags'
    | '/api/public/flags'
    | '/api/internal/flags/$capabilityName'
    | '/api/internal/flags/history'
    | '/api/public/flags/$capabilityName'
    | '/api/internal/flags/$capabilityName/$controlName'
    | '/api/public/flags/$capabilityName/$controlName'
    | '/api/internal/flags/$capabilityName/$controlName/history'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/internal/flags'
    | '/api/public/flags'
    | '/api/internal/flags/$capabilityName'
    | '/api/internal/flags/history'
    | '/api/public/flags/$capabilityName'
    | '/api/internal/flags/$capabilityName/$controlName'
    | '/api/public/flags/$capabilityName/$controlName'
    | '/api/internal/flags/$capabilityName/$controlName/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiInternalFlagsRoute: typeof ApiInternalFlagsRouteWithChildren
  ApiPublicFlagsRoute: typeof ApiPublicFlagsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flags': {
      id: '/api/public/flags'
      path: '/api/public/flags'
      fullPath: '/api/public/flags'
      preLoaderRoute: typeof ApiPublicFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/flags': {
      id: '/api/internal/flags'
      path: '/api/internal/flags'
      fullPath: '/api/internal/flags'
      preLoaderRoute: typeof ApiInternalFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flags/$capabilityName': {
      id: '/api/public/flags/$capabilityName'
      path: '/$capabilityName'
      fullPath: '/api/public/flags/$capabilityName'
      preLoaderRoute: typeof ApiPublicFlagsCapabilityNameRouteImport
      parentRoute: typeof ApiPublicFlagsRoute
    }
    '/api/internal/flags/history': {
      id: '/api/internal/flags/history'
      path: '/history'
      fullPath: '/api/internal/flags/history'
      preLoaderRoute: typeof ApiInternalFlagsHistoryRouteImport
      parentRoute: typeof ApiInternalFlagsRoute
    }
    '/api/internal/flags/$capabilityName': {
      id: '/api/internal/flags/$capabilityName'
      path: '/$capabilityName'
      fullPath: '/api/internal/flags/$capabilityName'
      preLoaderRoute: typeof ApiInternalFlagsCapabilityNameRouteImport
      parentRoute: typeof ApiInternalFlagsRoute
    }
    '/api/public/flags/$capabilityName/$controlName': {
      id: '/api/public/flags/$capabilityName/$controlName'
      path: '/$controlName'
      fullPath: '/api/public/flags/$capabilityName/$controlName'
      preLoaderRoute: typeof ApiPublicFlagsCapabilityNameControlNameRouteImport
      parentRoute: typeof ApiPublicFlagsCapabilityNameRoute
    }
    '/api/internal/flags/$capabilityName/$controlName': {
      id: '/api/internal/flags/$capabilityName/$controlName'
      path: '/$controlName'
      fullPath: '/api/internal/flags/$capabilityName/$controlName'
      preLoaderRoute: typeof ApiInternalFlagsCapabilityNameControlNameRouteImport
      parentRoute: typeof ApiInternalFlagsCapabilityNameRoute
    }
    '/api/internal/flags/$capabilityName/$controlName/history': {
      id: '/api/internal/flags/$capabilityName/$controlName/history'
      path: '/history'
      fullPath: '/api/internal/flags/$capabilityName/$controlName/history'
      preLoaderRoute: typeof ApiInternalFlagsCapabilityNameControlNameHistoryRouteImport
      parentRoute: typeof ApiInternalFlagsCapabilityNameControlNameRoute
    }
  }
}

interface ApiInternalFlagsCapabilityNameControlNameRouteChildren {
  ApiInternalFlagsCapabilityNameControlNameHistoryRoute: typeof ApiInternalFlagsCapabilityNameControlNameHistoryRoute
}

const ApiInternalFlagsCapabilityNameControlNameRouteChildren: ApiInternalFlagsCapabilityNameControlNameRouteChildren =
  {
    ApiInternalFlagsCapabilityNameControlNameHistoryRoute:
      ApiInternalFlagsCapabilityNameControlNameHistoryRoute,
  }

const ApiInternalFlagsCapabilityNameControlNameRouteWithChildren =
  ApiInternalFlagsCapabilityNameControlNameRoute._addFileChildren(
    ApiInternalFlagsCapabilityNameControlNameRouteChildren,
  )

interface ApiInternalFlagsCapabilityNameRouteChildren {
  ApiInternalFlagsCapabilityNameControlNameRoute: typeof ApiInternalFlagsCapabilityNameControlNameRouteWithChildren
}

const ApiInternalFlagsCapabilityNameRouteChildren: ApiInternalFlagsCapabilityNameRouteChildren =
  {
    ApiInternalFlagsCapabilityNameControlNameRoute:
      ApiInternalFlagsCapabilityNameControlNameRouteWithChildren,
  }

const ApiInternalFlagsCapabilityNameRouteWithChildren =
  ApiInternalFlagsCapabilityNameRoute._addFileChildren(
    ApiInternalFlagsCapabilityNameRouteChildren,
  )

interface ApiInternalFlagsRouteChildren {
  ApiInternalFlagsCapabilityNameRoute: typeof ApiInternalFlagsCapabilityNameRouteWithChildren
  ApiInternalFlagsHistoryRoute: typeof ApiInternalFlagsHistoryRoute
}

const ApiInternalFlagsRouteChildren: ApiInternalFlagsRouteChildren = {
  ApiInternalFlagsCapabilityNameRoute:
    ApiInternalFlagsCapabilityNameRouteWithChildren,
  ApiInternalFlagsHistoryRoute: ApiInternalFlagsHistoryRoute,
}

const ApiInternalFlagsRouteWithChildren =
  ApiInternalFlagsRoute._addFileChildren(ApiInternalFlagsRouteChildren)

interface ApiPublicFlagsCapabilityNameRouteChildren {
  ApiPublicFlagsCapabilityNameControlNameRoute: typeof ApiPublicFlagsCapabilityNameControlNameRoute
}

const ApiPublicFlagsCapabilityNameRouteChildren: ApiPublicFlagsCapabilityNameRouteChildren =
  {
    ApiPublicFlagsCapabilityNameControlNameRoute:
      ApiPublicFlagsCapabilityNameControlNameRoute,
  }

const ApiPublicFlagsCapabilityNameRouteWithChildren =
  ApiPublicFlagsCapabilityNameRoute._addFileChildren(
    ApiPublicFlagsCapabilityNameRouteChildren,
  )

interface ApiPublicFlagsRouteChildren {
  ApiPublicFlagsCapabilityNameRoute: typeof ApiPublicFlagsCapabilityNameRouteWithChildren
}

const ApiPublicFlagsRouteChildren: ApiPublicFlagsRouteChildren = {
  ApiPublicFlagsCapabilityNameRoute:
    ApiPublicFlagsCapabilityNameRouteWithChildren,
}

const ApiPublicFlagsRouteWithChildren = ApiPublicFlagsRoute._addFileChildren(
  ApiPublicFlagsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiInternalFlagsRoute: ApiInternalFlagsRouteWithChildren,
  ApiPublicFlagsRoute: ApiPublicFlagsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
