/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFlagsRouteImport } from './routes/api/flags'
import { Route as ApiFlagsHistoryRouteImport } from './routes/api/flags.history'
import { Route as ApiFlagsCapabilityNameRouteImport } from './routes/api/flags.$capabilityName'
import { Route as ApiFlagsCapabilityNameControlNameRouteImport } from './routes/api/flags.$capabilityName.$controlName'
import { Route as ApiFlagsCapabilityNameControlNameHistoryRouteImport } from './routes/api/flags.$capabilityName.$controlName.history'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlagsRoute = ApiFlagsRouteImport.update({
  id: '/api/flags',
  path: '/api/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlagsHistoryRoute = ApiFlagsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ApiFlagsRoute,
} as any)
const ApiFlagsCapabilityNameRoute = ApiFlagsCapabilityNameRouteImport.update({
  id: '/$capabilityName',
  path: '/$capabilityName',
  getParentRoute: () => ApiFlagsRoute,
} as any)
const ApiFlagsCapabilityNameControlNameRoute =
  ApiFlagsCapabilityNameControlNameRouteImport.update({
    id: '/$controlName',
    path: '/$controlName',
    getParentRoute: () => ApiFlagsCapabilityNameRoute,
  } as any)
const ApiFlagsCapabilityNameControlNameHistoryRoute =
  ApiFlagsCapabilityNameControlNameHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ApiFlagsCapabilityNameControlNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/flags': typeof ApiFlagsRouteWithChildren
  '/api/flags/$capabilityName': typeof ApiFlagsCapabilityNameRouteWithChildren
  '/api/flags/history': typeof ApiFlagsHistoryRoute
  '/api/flags/$capabilityName/$controlName': typeof ApiFlagsCapabilityNameControlNameRouteWithChildren
  '/api/flags/$capabilityName/$controlName/history': typeof ApiFlagsCapabilityNameControlNameHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/flags': typeof ApiFlagsRouteWithChildren
  '/api/flags/$capabilityName': typeof ApiFlagsCapabilityNameRouteWithChildren
  '/api/flags/history': typeof ApiFlagsHistoryRoute
  '/api/flags/$capabilityName/$controlName': typeof ApiFlagsCapabilityNameControlNameRouteWithChildren
  '/api/flags/$capabilityName/$controlName/history': typeof ApiFlagsCapabilityNameControlNameHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/flags': typeof ApiFlagsRouteWithChildren
  '/api/flags/$capabilityName': typeof ApiFlagsCapabilityNameRouteWithChildren
  '/api/flags/history': typeof ApiFlagsHistoryRoute
  '/api/flags/$capabilityName/$controlName': typeof ApiFlagsCapabilityNameControlNameRouteWithChildren
  '/api/flags/$capabilityName/$controlName/history': typeof ApiFlagsCapabilityNameControlNameHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/api/flags'
    | '/api/flags/$capabilityName'
    | '/api/flags/history'
    | '/api/flags/$capabilityName/$controlName'
    | '/api/flags/$capabilityName/$controlName/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/api/flags'
    | '/api/flags/$capabilityName'
    | '/api/flags/history'
    | '/api/flags/$capabilityName/$controlName'
    | '/api/flags/$capabilityName/$controlName/history'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/api/flags'
    | '/api/flags/$capabilityName'
    | '/api/flags/history'
    | '/api/flags/$capabilityName/$controlName'
    | '/api/flags/$capabilityName/$controlName/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ApiFlagsRoute: typeof ApiFlagsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flags': {
      id: '/api/flags'
      path: '/api/flags'
      fullPath: '/api/flags'
      preLoaderRoute: typeof ApiFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flags/history': {
      id: '/api/flags/history'
      path: '/history'
      fullPath: '/api/flags/history'
      preLoaderRoute: typeof ApiFlagsHistoryRouteImport
      parentRoute: typeof ApiFlagsRoute
    }
    '/api/flags/$capabilityName': {
      id: '/api/flags/$capabilityName'
      path: '/$capabilityName'
      fullPath: '/api/flags/$capabilityName'
      preLoaderRoute: typeof ApiFlagsCapabilityNameRouteImport
      parentRoute: typeof ApiFlagsRoute
    }
    '/api/flags/$capabilityName/$controlName': {
      id: '/api/flags/$capabilityName/$controlName'
      path: '/$controlName'
      fullPath: '/api/flags/$capabilityName/$controlName'
      preLoaderRoute: typeof ApiFlagsCapabilityNameControlNameRouteImport
      parentRoute: typeof ApiFlagsCapabilityNameRoute
    }
    '/api/flags/$capabilityName/$controlName/history': {
      id: '/api/flags/$capabilityName/$controlName/history'
      path: '/history'
      fullPath: '/api/flags/$capabilityName/$controlName/history'
      preLoaderRoute: typeof ApiFlagsCapabilityNameControlNameHistoryRouteImport
      parentRoute: typeof ApiFlagsCapabilityNameControlNameRoute
    }
  }
}

interface ApiFlagsCapabilityNameControlNameRouteChildren {
  ApiFlagsCapabilityNameControlNameHistoryRoute: typeof ApiFlagsCapabilityNameControlNameHistoryRoute
}

const ApiFlagsCapabilityNameControlNameRouteChildren: ApiFlagsCapabilityNameControlNameRouteChildren =
  {
    ApiFlagsCapabilityNameControlNameHistoryRoute:
      ApiFlagsCapabilityNameControlNameHistoryRoute,
  }

const ApiFlagsCapabilityNameControlNameRouteWithChildren =
  ApiFlagsCapabilityNameControlNameRoute._addFileChildren(
    ApiFlagsCapabilityNameControlNameRouteChildren,
  )

interface ApiFlagsCapabilityNameRouteChildren {
  ApiFlagsCapabilityNameControlNameRoute: typeof ApiFlagsCapabilityNameControlNameRouteWithChildren
}

const ApiFlagsCapabilityNameRouteChildren: ApiFlagsCapabilityNameRouteChildren =
  {
    ApiFlagsCapabilityNameControlNameRoute:
      ApiFlagsCapabilityNameControlNameRouteWithChildren,
  }

const ApiFlagsCapabilityNameRouteWithChildren =
  ApiFlagsCapabilityNameRoute._addFileChildren(
    ApiFlagsCapabilityNameRouteChildren,
  )

interface ApiFlagsRouteChildren {
  ApiFlagsCapabilityNameRoute: typeof ApiFlagsCapabilityNameRouteWithChildren
  ApiFlagsHistoryRoute: typeof ApiFlagsHistoryRoute
}

const ApiFlagsRouteChildren: ApiFlagsRouteChildren = {
  ApiFlagsCapabilityNameRoute: ApiFlagsCapabilityNameRouteWithChildren,
  ApiFlagsHistoryRoute: ApiFlagsHistoryRoute,
}

const ApiFlagsRouteWithChildren = ApiFlagsRoute._addFileChildren(
  ApiFlagsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ApiFlagsRoute: ApiFlagsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
